# Use Debian Bookworm as the base image
FROM docker.s.thusaac.com:12711/library/debian:bookworm AS BUILDER
ENV DEBIAN_FRONTEND=noninteractive

# Install system dependencies
# RUN sed -i 's|http://deb.debian.org/|https://mirrors.tuna.tsinghua.edu.cn/|g' /etc/apt/sources.list.d/debian.sources
RUN apt-get update
# dependency generated by ChatGPT
RUN apt-get install -y \
    build-essential \
    make \
    gcc \
    g++ \
    autoconf \
    automake \
    libtool \
    pkg-config \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    python3 \
    python3-venv \
    python3-pip

# Set the working directory
WORKDIR /app
# Ensure the virtual environment is activated automatically
# ENV PATH="venv/bin:$PATH"

# Copy files from the host into the container
# COPY . .
COPY Umicollapse  /app/Umicollapse
COPY hisat-3n  /app/hisat-3n
COPY htslib /app/htslib
COPY samtools /app/samtools
COPY build.sh /app/build.sh

RUN chmod +x build.sh && ./build.sh


# Use Debian Bookworm as the base image
FROM docker.s.thusaac.com:12711/library/debian:bookworm
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
apt-get install -y openjdk-17-jre-headless && \
apt-get install -y numactl && \
apt-get install -y python3 
# apt-get install -y python3-pip && \
# apt-get install -y python3-venv

# WORKDIR /app
COPY --from=builder /app /app
# COPY Snakefile /app/Snakefile
# COPY Snakefile-stage2 /app/Snakefile-stage2

ENV PATH="/app/venv/bin:$PATH"
RUN mkdir /data

WORKDIR /script
# Set the default command
CMD ["bash"]

