# Use Debian Bookworm as the base image
FROM docker.s.thusaac.com:12711/library/debian:bookworm AS BUILDER
ENV DEBIAN_FRONTEND=noninteractive

# Install system dependencies
# RUN sed -i 's|http://deb.debian.org/|https://mirrors.tuna.tsinghua.edu.cn/|g' /etc/apt/sources.list.d/debian.sources
RUN apt-get update
# dependency generated by ChatGPT
RUN apt-get install -y \
    build-essential \
    make \
    gcc \
    g++ \
    autoconf \
    automake \
    libtool \
    pkg-config \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    python3 \
    python3-venv \
    python3-pip

# Set the working directory
WORKDIR /app
# Ensure the virtual environment is activated automatically
ENV PATH="venv/bin:$PATH"

# Copy files from the host into the container
COPY . .
RUN chmod +x build.sh && ./build.sh

# Use Debian Bookworm as the base image
FROM docker.s.thusaac.com:12711/library/debian:bookworm
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y openjdk-17-jre-headless
RUN apt-get install -y python3
RUN apt-get install -y python3-pip
RUN apt-get install -y python3-venv
RUN apt-get install -y numactl

WORKDIR /app
COPY --from=builder /app /app
ENV PATH="venv/bin:$PATH"
RUN mkdir /data

# Set the default command
CMD ["bash"]

